---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: ansible-molecule-wordpress
    image: asia.gcr.io/nonprod-utility-233414/infra/ansible
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      vault_password_file: "${HOME}/.ssh/.vault"
